services:
  postgres:
    image: postgres:16
    container_name: field-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: field_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ankita1234@
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
